version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-notes
    environment:
      POSTGRES_USER: notesuser
      POSTGRES_PASSWORD: notespass
      POSTGRES_DB: notesapp
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notesuser -d notesapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
